### ISSUE TITLE
Doesn't correctly handle repeated references

### ISSUE THREAD

**Issue by chocolateboy** [yeoman/stringify-object#15]
### test.js

```javascript
var pp = require('stringify-object');

var value = { value: 42 };
var object = { foo: value, bar: value };

console.log(pp(object));
```

### output

```
{
	foo: {
		value: 42
	},
	bar: null
}
```

`object.bar` is not a circular reference. It's just a reference that has already been seen in `object`, which is [not the same thing](https://github.com/chocolateboy/Hash-Fold/blob/v0.1.1/lib/Hash/Fold.pm#L226-L232).

Also, I expected "handles circular references" to mean they're flagged e.g. with `[Circular]` like `util.inspect`, rather than `null`, which, IMO, is misleading (even though it's documented). I just spent a fair bit of time trying to track down what I assumed was a bug in my code that was causing a value to be set to null only to find that it's not actually null...

**Comment by sindresorhus** [comment]
I agree with returning `[Circular]`. In hindsight returning `null` was a mistake. Fixed now.

I've also fixed the false positive on the circular reference thingy. Turns out I forgot to remove it from seen after recursing.
