### ISSUE TITLE
Fix bug when stringify an object with function property

### ISSUE THREAD

**Issue by danilosampaio** [yeoman/stringify-object#17]
Fix bug when stringify an object with `function` property:

Example: ```obj = {a: 1, b: function(){}}```

```
TypeError: Object function (){} has no method 'replace'
      at stringify (index.js:69:21)
      at ret (index.js:57:45)
      at Array.map (native)
      at stringify (index.js:50:30)
      at module.exports (index.js:70:4)
      at Context.<anonymous> (test.js:64:15)
```
	  
`JSON.stringify` "ignores" function properties, stringifying those properties as "null".

Example:
	  
JSON.stringify({a:1, b: function a(){}})
"{"a":1}"

JSON.stringify({a:1, b: [function(){}]})
"{"a":1,"b":[null]}"

shouldn't stringify-object treat it in the same way?

in my case, i added this check at the top of function:

```
if (typeof val === 'function'){
	return null;	
}
```

p.s. this error raised after commit a523397, that changed isObject() function.

**Comment by sindresorhus** [comment]
https://github.com/yeoman/stringify-object/commit/a523397aba9cb8f3f05482d3e8b2d41182d98756 was actually a bug fix as the previous object check was incorrect and hid this issue.

Does it make sense to return `null` or would you prefer to get the actual function source there by doing `fn.toString()`?

I guess we should also have a better fall through for unhandled types.

**Comment by danilosampaio** [comment]
> Does it make sense to return null or would you prefer to get the actual function source there by doing fn.toString()?

In fact, i prefer `fn.toString()`, as it is less intrusive then return `null`.

> I guess we should also have a better fall through for unhandled types.

I agree, and my suggestion to avoid unhandled type erros, is to create the following function: 

```
function escape(val, opts) {
	if (typeof val !== 'string') { 
		val = '' + val;  //HERE ANY UNHANDLED WILL BE STRINGIFYED
	}

	if (opts.singleQuotes === false) {
		return '"' + val.replace(/"/g, '\\\"') + '"';
	}

	return '\'' + val.replace(/'/g, '\\\'') + '\'';
}
```

and at the bottom of main function, just call `escape(val, opts)`.

this way, the following check is not necessary anymore:
```
if (typeof val === 'function'){
    return null;    
}
```

what do you think?
