### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by peterjwest** [yeoman/stringify-object#23]
Can someone clarify the license of this project? It appears to have been released under the MIT license for nearly a year, but has recently been updated to name the BSD license.

I would assume the MIT license either still applies or applies to versions of the code up until the new license was added.

**Comment by sindresorhus** [comment]
Oh, that was added by mistake. It was always considered to be `BSD-2-Clause`.

Fixed https://github.com/yeoman/stringify-object/commit/6468246134e3cebae245b5d428bcd6e144959526

**Comment by hrieke** [comment]
This should be documented as part of the readme file.
