### ISSUE TITLE
Option for specify acceptable width of text line

### ISSUE THREAD

**Issue by veged** [yeoman/stringify-object#25]
It will be great to have possibility to specify width and to allow `stringify-object` join short lines together. For example, instead of
```js
{
    a: 1,
    b: 2
}
```
I prefer to have
```js
{ a: 1, b: 2 }
```
if it fits my comport line width.

**Comment by sindresorhus** [comment]
No thanks. This is not a code formatting tool. You could use something like [esformatter](https://github.com/millermedeiros/esformatter) afterwards for that.
