### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [yeoman/stringify-object#29]
Would you please add a LICENSE file to the package, complete with the copyright information and the text of the BSD license?  The BSD license requires that the license text accompany the source code, and it makes it a lot easier for people like me to build packages for Linux distributions if the LICENSE file exists.

**Comment by eddiemonge** [comment]
i really dislike licenses and all the headaches associated with them. The license used here is a common one: https://spdx.org/licenses/BSD-2-Clause.html#licenseText so it doesn't need to be included, i think: https://docs.npmjs.com/files/package.json#license

**Comment by jaredsmith** [comment]
I know that licenses can be a pain, but in this case the two clauses of the BSD 2-clause license **specifically** say that the text must accompany the source code -- not just be referenced:

> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

In addition, simply referencing a well-known license doesn't explain who the copyright applies to.  For those reasons, I'm asking that you copy the text of the BSD 2-clause license, add the copyright information to the top, and put it in a LICENSE file.  If it's easier, I'll even do the legwork of building a pull request if you'll tell me who to attribute for copyright purposes and the year(s) of the copyright.

**Comment by eddiemonge** [comment]
Actually they say `Redistributions`, not distributions themselves. If you want to though, just copy it from https://github.com/yeoman/generator/blob/master/LICENSE
