### ISSUE TITLE
Option for trailing commas

### ISSUE THREAD

**Issue by vjpr** [yeoman/stringify-object#33]
Use case is generating a json value for a variable. When eslinting with trailing commas this is neccessary.

Should probably support all the eslint json settings really.

Similar issue from json5: https://github.com/json5/json5/issues/66

---

eslint has a fix option for the rule `comma-dangle`. https://github.com/eslint/eslint/blob/master/lib/rules/comma-dangle.js#L161

**Comment by sindresorhus** [comment]
Out of scope for this project, unfortunately. Fork or find something that's intended to be fully configurable.
