### ISSUE TITLE
v3 breaks Webpack / UglifyJS bundling process

### ISSUE THREAD

**Issue by natorojr** [yeoman/stringify-object#35]
I've been using the stringify-object package for quite some time in _both_ my Node projects and Web projects. Recently, I upgraded from v2.4.0 to v3.1.0 and that broke my Webpack build process as follows:

```
ERROR in app.22a5f0a6.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [../~/stringify-object/index.js:6,0]
```

Seems like [this line](https://github.com/yeoman/stringify-object/blob/v3.1.0/index.js#L6) is the culprit.

If I change that line to regular `function` syntax notation (instead of ES6 arrow syntax), it seems to fix the problem.

Any ideas why Uglify would complain there?

I use stringify-object heavily for debugging purposes throughout my projects, so I'd love to get this fixed.

**Comment by sindresorhus** [comment]
Uglify doesn't support ES2015. It's up to you to transpile with Babel or stay at the older version.

Explanation: https://github.com/sindresorhus/file-type/issues/70#issuecomment-268853935
