### ISSUE TITLE
publish precompiled version to npm

### ISSUE THREAD

**Issue by Xiphe** [yeoman/stringify-object#36]
this module is used in frontend applications (for example via [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string/blob/master/package.json#L51))

since babel/webpack normaly ignore `node_modules` it would be really helpful if this package could just provide es5 code.

**Comment by sindresorhus** [comment]
No. Reasoning: https://github.com/sindresorhus/file-type/issues/70
