### ISSUE TITLE
Would like a configurable handling for linebreaks.

### ISSUE THREAD

**Issue by stefanheine** [yeoman/stringify-object#38]
Have a look at this example code:

```
'use strict';

const stringifyObject = require('stringify-object');
const paths = 'Windows path is c:\\Windows\\path\\to\\node\nLinux is /tmp/nowhere';

console.log(stringifyObject(paths));
```

it results in the output:

> 'Windows path is c:\Windows\path\to\node\nLinux is /tmp/nowhere'

The bad thing about this is, that in the output I cannot see a difference between the `\n` that came in from the windows path and the one that came in from the line break.

To avoid this, I would like to have a configuration option that allows me to prevent the linebreak handling.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but not interested in having more options in this module.

**Comment by stefanheine** [comment]
Do you have any recommendations on how to work around the issue?
