### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by khoomeister** [yeoman/stringify-object#43]
Would you accept types for stringify-object?  I prefer them in the package, but I understand a maintainer's aversion if they're not familiar with TypeScript.  I can put up a PR if you're fine with it, otherwise I can put them on DefinitelyTyped.  LMK, thx!

**Comment by SBoudrias** [comment]
I don't think we'd end up maintaining these types. Probably better to send them on DefinitelyTyped.

**Comment by khoomeister** [comment]
OK thx
