### ISSUE TITLE
Possible to remove quotes?

### ISSUE THREAD

**Issue by komushi** [yeoman/stringify-object#48]
This is rather a question/request.
Is it an option like below to remove the quotes from the result?

```
const myObj = { ar: "myVar1" };
console.log(stringifyObject(obj, {myVar1: "noquotes"}));
>> {ar: myVar1}
```

**Comment by sindresorhus** [comment]
Why? What do you need it for?

**Comment by komushi** [comment]
When the output of stringifyObject is to have myVar1 as a variable not a string value.
It would be nice to have it.

**Comment by sindresorhus** [comment]
That's not really in the scope of this module.
