### ISSUE TITLE
`get-own-enumerable-proeprty-symbols` package breaks build using `create-react-app`

### ISSUE THREAD

**Issue by chrisjpatty** [yeoman/stringify-object#49]
```
static/js/main.9306e5d5.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/get-own-enumerable-property-symbols/index.js:1,0]
```
I receive this error when running the default build script that ships with `create-react-app`. I'm on version 3.2.0 of `stringify-object`

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446
