### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by OriR** [yeoman/stringify-object#53]
Not sure if this was meant to be used in a browser or not, but I do, through one of the packages that I'm using.
The current version is only published with ES2015+ syntax, meaning it can't be used in IE11.
Is there a chance to also compile it down to ES5?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
