### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by HarrisonDing** [yeoman/stringify-object#58]
I use react-create-app, and I use stringify-object to format json code, it is work when using 'npm start'.
But when I build the code by 'npm run build', it caused the issue as title.

From create-react-app's troubleshooting:
"Some third-party packages don't compile their code to ES5 before publishing to npm."

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
