### ISSUE TITLE
Not support another style 

### ISSUE THREAD

**Issue by zhaoleipeng** [yeoman/stringify-object#60]
please add option to support this style object.
``` 
{
  'post-id-followup-log-c79b15': {
    status: {
      name: 'xxxx',
      type: 'string',
    },
    purchaseType: {
      allowNull: false,
      name: 'xxxx',
      type: 'number',
    },
}
```
always has comma on the end

**Comment by sindresorhus** [comment]
This module is for just printing an object, not supporting every custom style out there. If you need to format it, check out https://github.com/prettier/prettier or `eslint --fix`.
