### ISSUE TITLE
create-react-app build: Failed to minify the code from this file

### ISSUE THREAD

**Issue by lucascassiano** [yeoman/stringify-object#62]
Hi, 
Using create-react-app (1.5.2) and stringify-object (3.3.0) i got the following error:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/stringify-object/index.js:6

Read more here: http://bit.ly/2tRViJ9
```

**Comment by sindresorhus** [comment]
Upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
