### ISSUE TITLE
can you transform your code by babel

### ISSUE THREAD

**Issue by stoneyallen** [yeoman/stringify-object#63]
my project need pretty the object, but when i build my code with webpack, i get these throw
`ERROR in Encountered an error while minifying burypoint_elastic.cbcd2752da8817a132a7.js:
SyntaxError: Unexpected token: keyword (const)`
because of your code is ES6, so i can't build codes successfully, can you babel this lib before publish
thank you very much!

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
