### ISSUE TITLE
'singleQuotes' option not applied on keys

### ISSUE THREAD

**Issue by vishalgakhare** [yeoman/stringify-object#67]
This could be enhancement.
I thought setting 'singleQuotes' to false will make all keys as well as values string.

```js
const logMessage = {name:'vishal'};
console.log(stringifyObject(logMessage, {singleQuotes: false}));
```
**Actual**:
```json
{
        name: "vishal"
}

```

**Expected**:
```json
 {"name":"vishal"}
```

**Comment by sindresorhus** [comment]
Force-quoting object keys are out of scope of this module. The point of this module is to generate a JS object. If you need quotes keys too, you can just use `JSON.stringify()`.

**Comment by vishalgakhare** [comment]
Okay. 
The stringify gives double quoted keys but doesn’t stringify nested object values. I thought this package solves that issue, giving true string value.
