### ISSUE TITLE
test with jest causing an exeption

### ISSUE THREAD

**Issue by huci75** [yeoman/stringify-object#76]
I have to test my code with the jest framework. But every time a test is calling stringifyObject with a object its crash with follow exception:

   TypeError: get_own_enumerable_property_symbols_1.default.default is not a function or its return value is not iterable

      336 |
      337 |   const obj = { status: 400, data: { code: 400, message: 'Test'} };
    > 338 |   const log = stringifyObject(obj);
          |               ^

 with a simply data type like string or number the test works fine. Here the example code

//util.ts
export function traceError() {
  const obj = { status: 400, data: { code: 400, message: 'Test'} };
  const log = stringifyObject(obj);
  console.log(log);
  return obj;
}

//util.test.ts
describe('functions', () => {
test('traceError should return 400', () => {
      const response = traceError();
      expect(response.status).toEqual(400);
});

Any solution for this?

**Comment by sindresorhus** [comment]
You should ask on the Jest issue tracker. This is not an issue with this package.
