### ISSUE TITLE
Lib fails for runtime that supports only commonjs

### ISSUE THREAD

**Issue by PatrykMilewski** [yeoman/stringify-object#79]
Hello,

When trying to use this lib with Jest, it fails because you are using ESM syntax (`import [...] from '[...]'`)

Would you consider exporting it in a fashion, that supports both CommonJS and ESM?

An article about the problem and how it should be done:
https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by sindresorhus** [comment]
No plans to do that. The problem is your Jest config.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
